name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint || true
        
      - name: Trigger Render Deploy Hook
        run: |
          curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        
      - name: Deployment notification
        run: |
          echo "Deployment triggered on Render.com"
